name = "eeg-training-discussion"
type = "javascript"

account_id = "dd6b8d03c02a0073850087728e5c1917"       # Your Cloudflare Account ID
workers_dev = true
route = ""
zone_id = ""

kv_namespaces = [
  { binding = "DISCUSSION_KV", id = "6278875977e24532be253f2704db4edd" }
]

r2_buckets = [
  { binding = "DISCUSSION_R2", bucket_name = "eeg-training-discussion-r2", preview_bucket_name = "eeg-training-discussion-r2" }
]